

services:
  dev-agent:
    dns:
      - ${DEVKIT_DNS_IP:-172.30.10.53}
    depends_on:
      - dns

  dns:
    image: andyshinn/dnsmasq:latest
    command: ["-k", "--conf-file=/etc/dnsmasq.d/dnsmasq.conf"]
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf:ro
    networks:
      dev-internal:
        ipv4_address: ${DEVKIT_DNS_IP:-172.30.10.53}
      dev-egress:
        aliases: [dns]

networks:
  dev-internal:
    ipam:
      driver: default
      config:
        - subnet: ${DEVKIT_INTERNAL_SUBNET:-172.30.10.0/24}
  dev-egress:
    driver: bridge
