

services:
  dev-agent:
    build:
      context: ../../ouroboros-ide
      dockerfile: docker/dev/codex-agent.Dockerfile
      args:
        INSTALL_CODEX: "${INSTALL_CODEX:-true}"
        INSTALL_CLAUDE: "${INSTALL_CLAUDE:-true}"
        JDK_VERSION: "${JDK_VERSION:-17}"
        CODEX_VERSION: "${CODEX_VERSION:-rust-v0.74.0}"
        CODEX_ASSET: "${CODEX_ASSET:-codex-x86_64-unknown-linux-musl.tar.gz}"
        CODEX_SHA256: "${CODEX_SHA256:-}"
        CLAUDE_VERSION: "${CLAUDE_VERSION:-latest}"
        AWSCLI_URL: "${AWSCLI_URL:-https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip}"
        AWSCLI_SHA256: "${AWSCLI_SHA256:-}"
    image: local/dev-agent:codex
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/workspace/.aws/credentials
      - AWS_CONFIG_FILE=/workspace/.aws/config
      - AWS_PROFILE=${AWS_PROFILE:-codex}
      - JAVA_TOOL_OPTIONS=-Dhttp.proxyHost=tinyproxy -Dhttp.proxyPort=8888 -Dhttps.proxyHost=tinyproxy -Dhttps.proxyPort=8888 -Djava.net.useSystemProxies=true
      - SBT_GLOBAL_BASE=/workspace/.devhome/.sbt
      - DOCKER_HOST=unix:///broker-run/postgres-broker.sock
      - TESTCONTAINERS_RYUK_DISABLED=true
    volumes:
      - ${WORKSPACE_DIR:-.}:/workspace:rw
      - ${DEVKIT_WORKTREE_ROOT}:${DEVKIT_WORKTREE_CONTAINER_ROOT:-/worktrees}:rw
      - ivy2-cache:/home/dev/.ivy2
      - coursier-cache:/home/dev/.cache/coursier
      - devkit-auth:/home/dev/.codex
      # Optional: mount host Codex config dir for seeding auth.json
      - ${HOST_CODEX_DIR:-${HOME}/.codex}:/var/host-codex:ro
      - ${HOST_CODEX_FILE:-${HOME}/.codex/auth.json}:/var/auth.json:ro
      - tmpfs:/tmp
      - broker-run:/broker-run
    depends_on:
      postgres-broker:
        condition: service_started

  postgres-broker:
    build:
      context: ../brokers/postgres-broker
      dockerfile: Dockerfile
    image: devkit/postgres-broker:dev
    user: "0:0"
    environment:
      - BROKER_LISTEN=unix:///broker-run/postgres-broker.sock
      - BROKER_UPSTREAM=/var/run/docker.sock
      - BROKER_ALLOWED_IMAGES=${BROKER_ALLOWED_IMAGES:-postgres:latest,minio/minio:latest}
      - BROKER_ALLOWED_IMAGE=${BROKER_ALLOWED_IMAGE:-postgres}
      - BROKER_ALLOWED_TAG=${BROKER_ALLOWED_TAG:-latest}
      - BROKER_ALLOW_PULLS=${BROKER_ALLOW_PULLS:-true}
      - BROKER_LOG_LEVEL=${BROKER_LOG_LEVEL:-info}
      - BROKER_ATTACH_NETWORKS=${BROKER_ATTACH_NETWORKS:-devkit_dev-internal}
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - broker-run:/broker-run
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-internal

volumes:
  broker-run:
